version: '2'
services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    networks:
    - mapproxy
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - mapproxy
  mapproxy:
    image: mapproxy:latest
    networks:
    - mapproxy
    environment:
    - PROCESSES=2
networks:
  mapproxy: {}
